---
all:
  hosts:
    MS1:
      ansible_host: 10.1.1.1
      ansible_user: khalid
      ansible_password: password
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password: password

    SchoolSwitch:
      ansible_host:
      ansible_user:
      ansible_password:
      ansible_network_os: ios
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password:
