---
all:
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  children:
    switches:
      vars:
        ansible_user: bob
        ansible_password: hello
        ansible_become_password: cisco
      hosts:
        Internet-Switch:
          ansible_host: 11.0.0.78
        Second-Switch:
          ansible_host: 11.0.0.79

    other_devices:
      hosts:
        MS1:
          ansible_host: 10.1.1.1
          ansible_user: khalid
          ansible_password: password
          ansible_become_password: password
