---
ansible-project:
  children:
    router:
      host:
        #I will add IP address later:
    switch:
      host:
        #I will add IP address later:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: #I will add later
    ansible_password: #I will add later